$.vali.setPrompt({
    "Success": "输入正确",
    "email": "请输入正确的邮箱地址",
    "phone": "请输入正确的手机号码",
    "phone_bl":"不支持：" ,
    "max": "长度不能超过｛0｝位",
    "min": "长度不能小于｛0｝位",
    "bank": "请输入正确的银行卡号",
    "only": "只能包含",
    "must": "必须包含",
    "first_must": "首位必须是",
    "first_cannot": "首位不能是",
    "number": "请输入正确合法的数字",
    "idcard": "请输入正确的身份证号",
    "equally": "必须一样",
    "cannot": "不能是｛0｝",
    "date": "请输入正确的日期格式",
    "http": "请输入正确的网址",
    "number_max": "不能大于 ｛0｝",
    "number_min": "不能小于 ｛0｝",
    "time": "请输入正确的时间格式",
    "datetime": "请输入正确的日期时间格式",
    "value0": "汉字",
    "value1": "字母",
    "value2": "数字",
    "value3": "空格字符"
});
